version: '3.1'

services:

  dot_db:
        image: datakindorg/dot_db_demo:latest
        container_name: dot-db
        ports:
            - "5433:5432"
        volumes:
          - ./demo/db/data:/var/lib/postgresql/data

  dot:
    image: datakindorg/dot_demo:latest
    container_name: dot

  appsmith:
    image: datakindorg/dot_appsmith:latest
    container_name: appsmith
    ports:
      - "82:80"
      - "446:443"
    volumes:
      - ./demo/appsmith/stacks:/appsmith-stacks
