version: '3.1'

services:
  dot_db:
      image: postgres:9.6.23-buster
      container_name: dot-db
      ports:
          - "5433:5432"
      environment:
          POSTGRES_DB: dot_db
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      volumes:
          - .:/db_dumps
          - ./db/data:/var/lib/postgresql/data
          - ../db/dot:/docker-entrypoint-initdb.d

  dot:
    build:
        context: ..
        dockerfile: ./docker/dot/Dockerfile
    image: dot
    container_name: dot
    environment:
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ../:/app
      - ./dot/dot_config.yml:/app/dot/config/dot_config.yml
      - ../dot/config/example/self_tests/dot_config_docker.yml:/app/dot/self_tests/data/base_self_test/dot_config.yml

  appsmith:
    image: index.docker.io/appsmith/appsmith-ce
    container_name: appsmith
    ports:
      - "82:80"
      - "446:443"
    volumes:
      - ./appsmith/stacks:/appsmith-stacks
    #restart: unless-stopped
    #   # Uncomment the lines below to enable auto-update
    #labels:
    #  com.centurylinklabs.watchtower.enable: "true"

  # appsmith auto-update
  #auto_update:
  #  image: containrrr/watchtower:latest-dev
  #  volumes:
  #    - /var/run/docker.sock:/var/run/docker.sock
  #  # Update check interval in seconds.
  #  command: --schedule "0 0 * ? * *" --label-enable --cleanup
  #  restart: unless-stopped

