config:
  partial_parse: False

default:
  target: dev
  outputs:
    dev:
      type: postgres
      host: dot_db
      user: postgres
      pass: password
      port: 5432
      dbname: dot_db
      schema: public
      threads: 4
