config:
  partial_parse: False

default:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      user: postgres
      pass: postgres
      port: 5432
      dbname: dot_db
      schema: self_tests_public
      threads: 4
