dot:
  save_passed_tests: False
  output_schema_suffix: tests
dot_db:
  type: postgres
  host: localhost
  user: postgres
  pass: postgres
  port: 5432
  dbname: dot_db
  schema: self_tests_dot
  threads: 4
ScanProject1_db:
  type: postgres
  host: localhost
  user: postgres
  pass: postgres
  port: 5432
  dbname: dot_db
  schema: self_tests_public
  threads: 4
